[workspace]
resolver = "2"
members = [
   "RsIskraMeter",
   "RsPaymentTerminal",
   "rust_examples/RsExample",
   "rust_examples/RsExampleUser",
]

[workspace.dependencies]
everestrs = { git = "https://github.com/everest/everest-framework.git", rev = "3e767e2a5652d3acb97d01fc88aae2f04f3f5282" }
everestrs-build = { git = "https://github.com/everest/everest-framework.git", rev = "3e767e2a5652d3acb97d01fc88aae2f04f3f5282" }
