[workspace]
resolver = "2"
members = [
   "RsIskraMeter",
   "RsPaymentTerminal",
   "rust_examples/RsExample",
   "rust_examples/RsExampleUser",
]

[workspace.dependencies]
everestrs = { git = "https://github.com/everest/everest-framework.git", tag = "v0.20.2" }
everestrs-build = { git = "https://github.com/everest/everest-framework.git", tag = "v0.20.2" }
