active_modules:
  iso15118_charger:
    module: PyJosev
    config_module:
      device: auto
      supported_DIN70121: false
  iso15118_car:
    module: JsCarV2G
    config_implementation:
      main:
        stack_implementation: RISE-V2G
        mqtt_base_path: everest_external/iso15118/ev
        device: auto
  connector_1:
    module: EvseManager
    config_module:
      connector_id: 1
      three_phases: true
      has_ventilation: true
      country_code: DE
      rcd_enabled: true
      evse_id: "1"
      session_logging: true
      session_logging_xml: false
      ac_hlc_enabled: false
      ac_hlc_use_5percent: false
      ac_enforce_hlc: false
    connections:
      bsp:
        - module_id: yeti_driver_1
          implementation_id: board_support
      powermeter_grid_side:
        - module_id: yeti_driver_1
          implementation_id: powermeter
      slac:
        - module_id: slac
          implementation_id: evse
      hlc:
        - module_id: iso15118_charger
          implementation_id: charger
  connector_2:
    module: EvseManager
    config_module:
      connector_id: 2
      three_phases: true
      has_ventilation: true
      country_code: DE
      rcd_enabled: true
      evse_id: "2"
      session_logging: true
      session_logging_xml: false
      ac_hlc_enabled: false
      ac_hlc_use_5percent: false
      ac_enforce_hlc: false
    connections:
      bsp:
        - module_id: yeti_driver_2
          implementation_id: board_support
      powermeter_grid_side:
        - module_id: yeti_driver_2
          implementation_id: powermeter
      slac:
        - module_id: slac
          implementation_id: evse
      hlc:
        - module_id: iso15118_charger
          implementation_id: charger
  yeti_driver_1:
    module: JsYetiSimulator
  yeti_driver_2:
    module: JsYetiSimulator
  slac:
    module: JsSlacSimulator
  car_simulator_1:
    module: JsCarSimulator
    config_module:
      connector_id: 1
      auto_enable: true
      auto_exec: false
      auto_exec_commands: sleep 1;iec_wait_pwr_ready;sleep 1;draw_power_regulated 16,3;sleep 30;unplug
    connections:
      simulation_control:
        - module_id: yeti_driver_1
          implementation_id: yeti_simulation_control
      ev:
        - module_id: iso15118_car
          implementation_id: ev
      slac:
        - module_id: slac
          implementation_id: ev
  car_simulator_2:
    module: JsCarSimulator
    config_module:
      connector_id: 2
      auto_enable: true
      auto_exec: false
    connections:
      simulation_control:
        - module_id: yeti_driver_2
          implementation_id: yeti_simulation_control
      ev:
        - module_id: iso15118_car
          implementation_id: ev
      slac:
        - module_id: slac
          implementation_id: ev
  ocpp:
    module: OCPP201
    config_module:
      ChargePointConfigPath: config.json
    connections:
      evse_manager:
        - module_id: connector_1
          implementation_id: evse
        - module_id: connector_2
          implementation_id: evse
      system:
        - module_id: system
          implementation_id: main
  auth:
    module: Auth
    config_module:
      connection_timeout: 30
      selection_algorithm: PlugEvents
    connections:
      token_provider:
        - module_id: ocpp
          implementation_id: auth_provider
        - module_id: token_provider_manual
          implementation_id: main
      token_validator:
        - module_id: ocpp
          implementation_id: auth_validator
      evse_manager:
        - module_id: connector_1
          implementation_id: evse
        - module_id: connector_2
          implementation_id: evse
  token_provider_manual:
    module: JsDummyTokenProviderManual
  energy_manager:
    module: EnergyManager
    connections:
      energy_trunk:
        - module_id: grid_connection_point
          implementation_id: energy_grid
  grid_connection_point:
    module: EnergyNode
    config_module:
      fuse_limit_A: 40.0
      phase_count: 3
    connections:
      price_information: []
      energy_consumer:
        - module_id: connector_1
          implementation_id: energy_grid
        - module_id: connector_2
          implementation_id: energy_grid
      powermeter:
        - module_id: yeti_driver_1
          implementation_id: powermeter
  api:
    module: API
    connections:
      evse_manager:
        - module_id: connector_1
          implementation_id: evse
  system:
    module: System

x-module-layout: {}
