name: Build and push all docker images

on:
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild of all images'
        default: false
        type: boolean
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request: {}

env:
  REGISTRY: ghcr.io

jobs:
  lint-versions:
    name: Ensure versions are consistent
    runs-on: 'ubuntu-22.04'
    defaults:
      run:
        working-directory: ./source
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source
      - name: Run version consistency check
        run: ./.ci/scripts/check_version_consistency.py --input .
  build-and-push-all-images:
    name: Build and push all docker images
    strategy:
      matrix:
        image_name: [everest-ci-env, everest-clang-format]
    uses: everest/everest-ci/.github/workflows/deploy-single-docker-image.yml@v1.1.0
    with:
      force_rebuild: ${{ inputs.force_rebuild || (github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/' )) || false }}
      image_name: ${{ matrix.image_name }}
      docker_directory: docker/
      docker_registry: ghcr.io
      github_ref_before: ${{ github.event.before }}
      github_ref_after: ${{ github.event.after }}
    secrets:
      SA_GITHUB_PAT: ${{ secrets.SA_GITHUB_PAT }}
      SA_GITHUB_USERNAME: ${{ secrets.SA_GITHUB_USERNAME }}
