active_modules:
  iso15118_charger:
    module: Evse15118D20
    config_module:
      device: auto
    connections:
      security:
        - module_id: evse_security
          implementation_id: main
  iso15118_car:
    module: PyEvJosev
    config_module:
      device: auto
      supported_DIN70121: false
      supported_ISO15118_2: false
      supported_ISO15118_20_DC: false
      supported_ISO15118_20_AC: true
      supported_d20_energy_services: "AC_BPT,AC"
      tls_active: true
      enable_tls_1_3: true
  evse_manager:
    module: EvseManager
    config_module:
      ac_enforce_hlc: false
      ac_hlc_enabled: true
      ac_hlc_use_5percent: false
      ac_nominal_voltage: 230
      supported_iso_ac_bpt: true
      charge_mode: AC
      connector_id: 1
      ev_receipt_required: false
      evse_id: DE*PNX*E12345*1
      has_ventilation: true
      max_current_import_A: 32
      max_current_export_A: 32
      payment_enable_contract: false
      payment_enable_eim: true
      session_logging: true
      session_logging_path: /tmp/everest-logs
      session_logging_xml: false
      switch_3ph1ph_delay_s: 5
      switch_3ph1ph_cp_state: X1
      bpt_channel: Unified
      bpt_generator_mode: GridFollowing
      bpt_grid_code_island_method: Passive
    connections:
      bsp:
        - module_id: connector_1_powerpath
          implementation_id: board_support
      hlc:
        - module_id: iso15118_charger
          implementation_id: charger
      powermeter_car_side:
        - module_id: connector_1_powerpath
          implementation_id: powermeter
      slac:
        - module_id: slac
          implementation_id: evse
      ac_rcd:
        - implementation_id: rcd
          module_id: connector_1_powerpath
      connector_lock:
        - implementation_id: connector_lock
          module_id: connector_1_powerpath
  connector_1_powerpath:
    config_module:
      connector_id: 1
    connections: {}
    module: YetiSimulator
    telemetry:
      id: 1  
  slac:
    module: SlacSimulator
  ev_manager:
    module: EvManager
    config_module:
      connector_id: 1
      auto_enable: true
      auto_exec: false
      auto_exec_commands: sleep 3;iso_wait_slac_matched;iso_start_v2g_session AC 86400 0;iso_wait_pwr_ready;iso_draw_power_regulated 16,3;iso_wait_for_stop 20;iso_wait_v2g_session_stopped;unplug
    connections:
      ev_board_support:
        - module_id: connector_1_powerpath
          implementation_id: ev_board_support
      ev:
        - module_id: iso15118_car
          implementation_id: ev
      slac:
        - module_id: slac
          implementation_id: ev
  auth:
    module: Auth
    config_module:
      connection_timeout: 10
      selection_algorithm: FindFirst
    connections:
      token_provider:
        - module_id: token_provider
          implementation_id: main
      token_validator:
        - module_id: token_validator
          implementation_id: main
      evse_manager:
        - module_id: evse_manager
          implementation_id: evse
  token_provider:
    module: DummyTokenProvider
    config_implementation:
      main:
        timeout: 10
        token: DEADBEEF
    connections:
      evse:
        - module_id: evse_manager
          implementation_id: evse
  token_validator:
    module: DummyTokenValidator
    config_implementation:
      main:
        validation_result: Accepted
        validation_reason: Token seems valid
        sleep: 0.25
  evse_security:
    module: EvseSecurity
    config_module:
      private_key_password: "123456"
  energy_manager:
    module: EnergyManager
    config_module:
      schedule_total_duration: 1
      schedule_interval_duration: 60
      debug: false
    connections:
      energy_trunk:
        - module_id: grid_connection_point
          implementation_id: energy_grid
  grid_connection_point:
    module: EnergyNode
    config_module:
      fuse_limit_A: 40.0
      phase_count: 3
    connections:
      price_information: []
      energy_consumer:
        - module_id: api_sink
          implementation_id: energy_grid
      powermeter:
        - module_id: connector_1_powerpath
          implementation_id: powermeter
  api_sink:
    module: EnergyNode
    mapping:
      module:
        evse: 1
    config_module:
      fuse_limit_A: 32.0
      phase_count: 3
    connections:
      energy_consumer:
        - module_id: evse_manager
          implementation_id: energy_grid
  api:
    module: API
    connections:
      evse_manager:
        - module_id: evse_manager
          implementation_id: evse
      error_history:
        - module_id: error_history
          implementation_id: error_history
      evse_energy_sink:
        - module_id: api_sink
          implementation_id: external_limits
  error_history:
    module: ErrorHistory
    config_implementation:
      error_history:
        database_path: /tmp/error_history.db
x-module-layout: {}
