active_modules:
  emgr_logger:
    module: JsEmgrLogger
    config_implementation:
      main:
        file_path_prefix: emgr_data
    connections:
      emgr:
        - module_id: energy_manager
          implementation_id: main
      pm_grid:
        - module_id: sma_modbus_meter
          implementation_id: main
      pm_ev:
        - module_id: yeti_driver
          implementation_id: powermeter
  energy_manager:
    module: JsEnergyManager
    config_implementation:
      main:
        pid_setpoint: 500
        pid_p_weight: 0.46
        pid_i_weight: 0.2
        pid_d_weight: 0.5
        pid_output_interval: 5000
        pid_i_limit: -1
        pid_min_output: 1380
        pid_max_output: 7360
    connections:
      chargingdriver:
        - module_id: evse_manager
          implementation_id: evse
      chargingdriverenergy:
        - module_id: evse_manager
          implementation_id: evse_energy_control
      gridpowermeter:
        - module_id: sma_modbus_meter
          implementation_id: main
      chargingdriverpowermeter:
        - module_id: yeti_driver
          implementation_id: powermeter
  iso15118_charger:
    module: EvseV2G
    config_module:
      device: auto
      tls_security: allow
  evse_manager:
    module: EvseManager
    config_module:
      three_phases: true
      has_ventilation: true
      country_code: DE
      rcd_enabled: true
    connections:
      bsp:
        - module_id: yeti_driver
          implementation_id: board_support
      powermeter:
        - module_id: yeti_driver
          implementation_id: powermeter
      auth:
        - module_id: auth
          implementation_id: main
  yeti_driver:
    module: YetiDriver
    config_module:
      serial_port: /dev/ttyUSB0
      baud_rate: 115200
  car_simulator:
    module: JsCarSimulator
    connections:
      simulation_control:
        - module_id: yeti_driver
          implementation_id: yeti_simulation_control
  auth:
    module: JsAuth
    connections:
      tokenProvider:
        - module_id: token_provider_1
          implementation_id: main
      tokenValidator:
        - module_id: token_validator
          implementation_id: main
  token_provider_1:
    module: JsDummyTokenProvider
    connections:
      evse:
        - module_id: evse_manager
          implementation_id: evse
  token_validator:
    module: JsDummyTokenValidator
    config_implementation:
      main:
        validation_result: Accepted
        validation_reason: Token seems valid
        sleep: 0.25
x-module-layout: {}
