settings:
  telemetry_enabled: true
active_modules:
  PowerMeter:
    module: PowermeterGSH01
    config_implementation:
      main:
        powermeter_device_id: 255
        serial_port: /dev/ttyUSB0
        baudrate: 115200
        parity: 0
        rs485_direction_gpio: -1
        ignore_echo: false
        gmt_offset_quarter_hours: 8
        publish_device_data: true
        publish_device_diagnostics: true