settings:
  telemetry_enabled: false
active_modules:
  auth:
    config_module:
      connection_timeout: 60
      prioritize_authorization_over_stopping_transaction: true
      selection_algorithm: FindFirst
      ignore_connector_faults: true
    connections:
      evse_manager:
        - implementation_id: evse
          module_id: connector_1
      token_provider:
        - implementation_id: main
          module_id: token_provider
      token_validator:
        - implementation_id: main
          module_id: token_validator
    module: Auth
  energy_manager:
    config_module:
      switch_3ph1ph_while_charging_mode: Both
      switch_3ph1ph_max_nr_of_switches_per_session: 5
      switch_3ph1ph_time_hysteresis_s: 20
      switch_3ph1ph_power_hysteresis_W: 1000
      switch_3ph1ph_switch_limit_stickyness: SinglePhase
      schedule_interval_duration: 60
      schedule_total_duration: 10
      debug: false
    connections:
      energy_trunk:
        - implementation_id: energy_grid
          module_id: grid_connection_point
    module: EnergyManager
  connector_1:
    config_module:
      ac_enforce_hlc: true
      ac_hlc_enabled: true
      ac_hlc_use_5percent: true
      ac_nominal_voltage: 230
      charge_mode: AC
      connector_id: 1
      ev_receipt_required: false
      evse_id: DE*PNX*E12345*1
      has_ventilation: true
      payment_enable_contract: false
      payment_enable_eim: true
      session_logging: true
      session_logging_path: /tmp/everest-logs
      session_logging_xml: false
      switch_3ph1ph_delay_s: 5
      switch_3ph1ph_cp_state: X1
      bpt_channel: Unified
      bpt_generator_mode: GridFollowing
      bpt_grid_code_island_method: Passive
    connections:
      bsp:
        - implementation_id: main
          module_id: cb_bsp
      hlc:
        - implementation_id: charger
          module_id: iso15118_charger
      powermeter_grid_side:
        - implementation_id: main
          module_id: powermeter
      slac:
        - implementation_id: main
          module_id: slac
      ac_rcd:
        - implementation_id: rcd
          module_id: cb_bsp
      connector_lock:
        - implementation_id: connector_lock
          module_id: cb_bsp
    module: EvseManager
    telemetry:
      id: 1
  grid_connection_point:
    config_module:
      fuse_limit_A: 16
      phase_count: 3
    connections:
      energy_consumer:
        - implementation_id: energy_grid
          module_id: connector_1
    module: EnergyNode
  iso15118_charger:
    module: Evse15118D20
    config_module:
      device: cb_plc
    connections:
      security:
        - module_id: evse_security
          implementation_id: main
    connections:
      security:
        - module_id: evse_security
          implementation_id: main
  evse_security:
    module: EvseSecurity
    config_module:
      private_key_password: "123456"
  persistent_store:
    config_module:
      sqlite_db_file_path: everest_persistent_store.db
    connections: {}
    module: PersistentStore
  slac:
    module: EvseSlac
    config_implementation:
      main:
        device: cb_plc
  token_provider:
    config_implementation:
      main:
        timeout: 10
        token: DEADBEEF
    connections:
      evse:
        - implementation_id: evse
          module_id: connector_1
    module: DummyTokenProvider
  token_validator:
    config_implementation:
      main:
        sleep: 0.25
        validation_reason: Token seems valid
        validation_result: Accepted
    connections: {}
    module: DummyTokenValidator
  cb_bsp:
    connections: {}
    module: evse_board_support_API
  powermeter:
    module: GenericPowermeter
    config_implementation:
      main:
        model: Eastron_SDM72DM
        powermeter_device_id: 1
    connections:
      serial_comm_hub:
        - module_id: commhub
          implementation_id: main
  commhub:
    module: SerialCommHub
    config_implementation:
      main:
        serial_port: /dev/cb_rs485
    
