[package]
name = "rs_example"
version = "0.1.0"
edition = "2021"

[dependencies]
everestrs = { path = "../../../../everest-framework/everestrs/everestrs" }
serde = { version = "1.0.175", features = ["derive"] }
serde_json = "1"
