settings:
  telemetry_enabled: false
active_modules:
  ocpp_api:
    module: ocpp_consumer_API
    config_module:
      cfg_communication_check_to_s: 0
    connections:
      ocpp:
        - module_id: cli
          implementation_id: ocpp
      data_transfer:
        - module_id: cli
          implementation_id: ocpp_data_transfer
  cli:
    module: BUOcppConsumer
    standalone: true
