
name: Manifests Test
on:
  workflow_call:
    inputs:
      runner:
        description: 'Which runner to use'
        required: false
        default: 'ubuntu-24.04'
        type: string


jobs:
  manifests_tes:
    name: Manifests Test
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: pip3 install pytest
      - name: Test manifests
        run: |
          cd ${{ github.workspace }}
          python3 -m pytest tests/manifest_tests/*.py
      
